Repository Madhesh-V/HacktoberFest-2023, pull requests merged in 2023-10, with the labels that each got.

#1 Create HelloWorld.java
  programs/HelloWorld.java
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#2 Parthasarathy27 patch 3
  employee.json
  programs/HelloWorld.java
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#3 Hello_mame
  lib/analysis_options.yaml
  lib/main.dart
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#4 Add my profile information
  participants/amarranjan1.md
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#5 Added My Information
  participants/kanizfatma.md
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#6 added myself
  participants/AmaanAnsari.md
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#7 added by rutuja
  participants/Rutuja.md
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023

#8 Ticket
  Railway-Reservation/application.properties
Labels: Hacktoberfest23, hacktoberfest2023-approved, hacktoberfest2023-accepted, hacktoberfest2023, Hacktoberfest

#9 Create beans
  Railway-Reservation/Ticket/beans
Labels: Hacktoberfest23, hacktoberfest2023-accepted, hacktoberfest2023, Hacktoberfest

#10 First code
  Railway-Reservation/Ticket/AdminBean.java
Labels: hacktoberfest2023-approved, hacktoberfest2023, Hacktoberfest

#11 Shalavya8103
  participants/Shalavya8103.md
  programs/quicksort.py
Labels: hacktoberfest2023-accepted, Hacktoberfest

#12 added user : prashantjagtap
  participants/prashantjagtap2909.md
Labels: hacktoberfest2023-accepted, Hacktoberfest

#14 Cost of Petrol
  programs/cost of petrol.py
Labels: hacktoberfest2023-accepted, Hacktoberfest

#13 Added Binary search algorithm
  programs/BinarySearch.cpp
Labels: hacktoberfest2023-approved, Hacktoberfest

#15 Create index.html
  EKart/index.html
Labels: hacktoberfest2023-approved, Hacktoberfest

#16 Create BinaryTree.cpp
  programs/BinaryTree.cpp
Labels: hacktoberfest2023-approved, Hacktoberfest

#21 Add files via upload
  Algorithams/C++/book_alo.cpp
Labels: hacktoberfest2023-accepted, Hacktoberfest

#20 Added Prims Algorithm
  Algorithams/C++/Prims-Algorithm.cpp
  participants/shrivardha.md
Labels: hacktoberfest2023-accepted, Hacktoberfest

#25 Create RohanRusta21.md
  participants/RohanRusta21.md
Labels: Hacktoberfest23, Hacktoberfest
